### ISSUE TITLE
_path helpers cause errors on namespaced route

### ISSUE THREAD

**Issue by counterbeing** [vladfaust/jbuilder-json_api#5]
I have an app I'm playing with that seems to blow up after when trying to access a helper that does not exist:

``` json
{
  "errors": [
    {
      "status": 500,
      "detail": "undefined method `book_path' for #<#<Class:0x007fca8a06cbe0>:0x007fca8ff7f240>",
      "title": "NoMethodError"
    }
  ]
}
```

I don't expect this helper to work, as I have everything namespaced under `v1`. The corresponding helper is `v1_book_path`. I took a quick peek at the code, and it looks like you build your helper from a string. Not sure if there's another way to do it...

Thanks! Love the project, and the ability to keep working with the familiar jbuilder.

**Comment by vladfaust** [comment]
@counterbeing I see a way in implementing a kind of `json_api_path` model method, may be a good one. But so many additional methods :disappointed:

**Comment by counterbeing** [comment]
Yeah, fair enough. Maybe it doesn’t make sense for this project.

Thanks for peeking!

**Comment by januszm** [comment]
So it seems like with this gem it is not possible to respond with URLs to resources? (Because the response content is generated in the model)

How would you implement this type of response:

```
{
"data": [
  {
    "id": "123",
    "type": "places",
    "attributes": {
      "name": "Foo Place!",
      "location": "1234 Elms st, Wayward Pines, Wyoming, 999666",
      "somefancymethod": "A return value"
    },
    "links": {
      "url": "http://localhost:3000/places/123"
    }
  },
...
]
}
```

I'm talking about URL part to be specific

**Comment by vitaly107** [comment]
do not waste time on this gem, not suitable for the purpose as outlined in the open issues. I had to structure jbuilder view manually at the end of the day.

**Comment by vladfaust** [comment]
@vitaly107 https://github.com/vladfaust/jbuilder-json_api/blob/master/MIT-LICENSE
